// Transcript export in every required format (spec 4.3 + Unicode 3.4).
// TXT / SRT: plain text blobs. DOCX: a real .docx via the `docx` library
// (Word does the Sinhala text shaping itself). PDF: the browser's print
// engine — the only client-side renderer that shapes Sinhala correctly.
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx'

function formatTime(sec) {
  const m = Math.floor(sec / 60)
  const s = Math.floor(sec % 60)
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

function srtTime(sec) {
  const h = String(Math.floor(sec / 3600)).padStart(2, '0')
  const m = String(Math.floor((sec % 3600) / 60)).padStart(2, '0')
  const s = String(Math.floor(sec % 60)).padStart(2, '0')
  const ms = String(Math.round((sec % 1) * 1000)).padStart(3, '0')
  return `${h}:${m}:${s},${ms}`
}

function download(blob, filename) {
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = filename
  a.click()
  URL.revokeObjectURL(a.href)
}

const baseName = (fileName) => fileName.replace(/\.[^.]+$/, '')

export function exportTxt(job, segments, textOf) {
  const lines = segments.map((s) => `[${formatTime(s.start)}] ${s.speaker}: ${textOf(s)}`)
  download(
    new Blob(['﻿' + lines.join('\n')], { type: 'text/plain;charset=utf-8' }),
    `${baseName(job.fileName)}_transcript.txt`,
  )
}

export function exportSrt(job, segments, textOf) {
  const blocks = segments.map(
    (s, i) => `${i + 1}\n${srtTime(s.start)} --> ${srtTime(s.end)}\n${s.speaker}: ${textOf(s)}\n`,
  )
  download(
    new Blob(['﻿' + blocks.join('\n')], { type: 'text/plain;charset=utf-8' }),
    `${baseName(job.fileName)}.srt`,
  )
}

export async function exportDocx(job, segments, textOf, classification) {
  const children = [
    new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun(job.fileName)] }),
    new Paragraph({
      children: [
        new TextRun({
          text: `${job.createdAt} · ${job.language || ''} · ${classification} · Generated by VoiceScript`,
          color: '888888',
          size: 18,
        }),
      ],
      spacing: { after: 300 },
    }),
  ]
  for (const s of segments) {
    children.push(
      new Paragraph({
        spacing: { before: 200 },
        children: [
          new TextRun({ text: s.speaker, bold: true }),
          new TextRun({ text: `   [${formatTime(s.start)}]`, color: '888888', size: 18 }),
        ],
      }),
      new Paragraph({ children: [new TextRun(textOf(s))] }),
    )
  }
  const doc = new Document({
    styles: {
      default: {
        document: { run: { font: 'Nirmala UI', size: 22 } },
      },
    },
    sections: [{ children }],
  })
  const blob = await Packer.toBlob(doc)
  download(blob, `${baseName(job.fileName)}_transcript.docx`)
}

export function exportPdf(job, segments, textOf, classification) {
  const esc = (t) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const rows = segments
    .map(
      (s) => `
      <div class="seg">
        <div class="meta"><b>${esc(s.speaker)}</b> <span>[${formatTime(s.start)}]</span></div>
        <p>${esc(textOf(s))}</p>
      </div>`,
    )
    .join('')
  const html = `<!doctype html><html><head><meta charset="utf-8">
    <title>${esc(job.fileName)} — transcript</title>
    <style>
      body { font-family: 'Noto Sans Sinhala', 'Nirmala UI', 'Iskoola Pota', 'Segoe UI', sans-serif;
             color: #111; margin: 40px; line-height: 1.65; }
      h1 { font-size: 20px; margin: 0 0 4px; }
      .sub { color: #777; font-size: 12px; margin-bottom: 26px; border-bottom: 1px solid #ddd; padding-bottom: 12px; }
      .seg { margin-bottom: 14px; page-break-inside: avoid; }
      .meta { font-size: 12px; margin-bottom: 2px; }
      .meta span { color: #999; }
      p { margin: 0; font-size: 14px; }
      @media print { body { margin: 18mm; } }
    </style></head><body>
    <h1>${esc(job.fileName)}</h1>
    <div class="sub">${esc(job.createdAt || '')} · ${esc(job.language || '')} · ${esc(classification)} · Generated by VoiceScript</div>
    ${rows}
    <script>window.onload = () => setTimeout(() => window.print(), 300)</script>
    </body></html>`
  const w = window.open('', '_blank')
  if (!w) {
    alert('Please allow pop-ups for this site to export PDF.')
    return
  }
  w.document.write(html)
  w.document.close()
}
